# -*- coding: utf-8 -*-
"""divar_ml_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xXuuLTxT_p9EWKe1ECDFN42BQkDvqZu9

# **Import libararies**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor

"""# **Reading dataset**"""

dataframe = pd.read_csv('divar_dataset.csv')

dataframe



"""# **Dataset overview**"""

dataframe.head()

dataframe.tail()

dataframe.info()

dataframe.describe()

dataframe.isnull().sum()

print(dataframe.duplicated().sum())

"""# **Exploratory Data Analysis And Insights**"""

dataframe['year_bins'] = (dataframe['manufacture_year']//5) * 5
dataframe['total_price_bilion'] = dataframe['total_price']/1e9

"""


> **This Chart Shows Us Number Of Rooms Per ManufactureYear**   

*   most of the houses in this dataset come with 2 rooms
*   most of the houses with 3 rooms are built in between 1395-1404
*   most of the houses with 1 rooms are belong to the 1385-1395
*   bigger houses are mostly comes with manufacture year of 1397-1404"""

sns.histplot(data=dataframe,x='rooms',kde=False,hue='year_bins',palette='Greens')
plt.show()

sns.histplot(data=dataframe,x='house_size',kde=False,hue='year_bins',palette='Greens')
plt.show()

"""


> **These Charts are about  the distribution of our features**   

*   most of the houses on **Divar** are between 1403-1404
*   most of the houseSize of **Tehran** is in between 50-110 meters
*   most of the houses of **Tehran** are selled in between 1-10 bilion Toman"""

columns = dataframe.columns[2:7]
num_columns = len(columns)
fig,axes = plt.subplots(1,num_columns,figsize=(6 * num_columns, 4))
for i,column in enumerate(columns):
  sns.histplot(data=dataframe,x = column,ax=axes[i],bins=50)
  axes[i].set_title(f'Distribution of {column}')
plt.tight_layout()
plt.show()

"""
> **These Charts are about the correlation between features**   

*  as we see, bigger house comes with more rooms
*  we see a linear-relation between total_price and house_size its says bigger house costs more money

* The last chart shows us that houses built in 1374 and 1395 are more expensive on average, respectively."""

corr_dataframe = dataframe.drop(columns=['year_bins','total_price_bilion'],axis=1)
sns.heatmap(data=corr_dataframe.corr(),fmt='.2f',annot=True)

sns.scatterplot(data=dataframe,x='total_price_bilion',y='house_size')
plt.xlabel('total_price(bilion)')
plt.ylabel('house_size')
plt.title('house_size vs total_price')
plt.show()

sns.scatterplot(data=dataframe,x='rooms',y='house_size')
plt.xlabel('rooms')
plt.ylabel('house_size')
plt.title('rooms vs house_size')
plt.show()

sns.scatterplot(data=dataframe,x='price_per_meter',y='total_price')
plt.xlabel('price_per_meter')
plt.ylabel('total_price')
plt.title('total_price vs price_per_meter')
plt.show()

sns.scatterplot(data=dataframe,x='manufacture_year',y='total_price')
plt.xlabel('manufacture_year')
plt.ylabel('total_price')
plt.title('Total_Price based Manufature_Year')
plt.show()

sns.scatterplot(data=dataframe,x='manufacture_year',y='house_size')
plt.xlabel('manufacture_year')
plt.ylabel('house_size')
plt.title('house_size based Manufature_Year')
plt.show()

avg_price_by_year = dataframe.groupby('manufacture_year')['total_price_bilion'].mean()
avg_price_by_year.plot(kind='bar', figsize=(12,5))
plt.ylabel("Average Total Price")
plt.title("Average House Total Price by Construction Year Bin")
plt.show()

"""# **Conclusion of insights**

 most of the ad-houses are **built-in** 1403-1404 , the newer houses has bigger size than older, most of the 100 meter and above house_size is belongs to 1397-1404 ad-houses and with that we know newer houses has more room than old houses in **average**.

#**Modeling**
"""

dataframe

X = dataframe.drop(columns = ['total_price','price_per_meter','year_bins','total_price_bilion'],axis=1)
y = dataframe['total_price']

X

y

"""#**split data into train and test set**"""

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

X_train

y_train

X_test

y_test

sc = StandardScaler()
X_train[['house_size','manufacture_year']] = sc.fit_transform(X_train[['house_size','manufacture_year']])
X_test[['house_size','manufacture_year']] = sc.transform(X_test[['house_size','manufacture_year']])

linear_regressor = LinearRegression()
linear_regressor.fit(X_train,y_train)

from sklearn.metrics import mean_absolute_error,root_mean_squared_error,r2_score
y_pred = linear_regressor.predict(X_test)

mae = mean_absolute_error(y_test,y_pred)
rmse = root_mean_squared_error(y_test,y_pred)
r2 = r2_score(y_test,y_pred)
mape = np.mean(np.abs((y_test - y_pred)/y_test)) * 100
print("for linear regression\n")
print(f"mae : {mae}")
print(f"rmse : {rmse}")
print(f"mspe : {mape:.2f}%")
print(f"r2Score : {r2}")

random_forest_regressor = RandomForestRegressor()
random_forest_regressor.fit(X_train,y_train)

y_pred_r = random_forest_regressor.predict(X_test)

mae = mean_absolute_error(y_test,y_pred_r)
rmse = root_mean_squared_error(y_test,y_pred_r)
r2 = r2_score(y_test,y_pred_r)
mape = np.mean(np.abs((y_test - y_pred_r)/y_test)) * 100
print("for randomForest regression\n")
print(f"mae : {mae}")
print(f"rmse : {rmse}")
print(f"mspe : {mape:.2f}%")
print(f"r2Score : {r2}")